### ISSUE TITLE
无法创建环境

### ISSUE THREAD

**Issue by zhongjianfeipqy** [FeatureProbe/feature-probe-api#34]
创建环境提示报错
![image](https://user-images.githubusercontent.com/16659942/197487241-798baf00-10c8-488d-80df-21b98aba963e.png)
![image](https://user-images.githubusercontent.com/16659942/197487261-1134e311-8c5e-4733-8760-2dba72d7fe1a.png)

**Comment by gangb-tech** [comment]
Fixed。
This error is caused by the test package。
