### ISSUE TITLE
标签问题

### ISSUE THREAD

**Issue by x3hong** [FeatureProbe/feature-probe-api#35]
我在Campaign Allow List 创建了标签，然后在开关列表中无法显示创建的标签内容，不知道这是不是个bug
如图：
![image](https://user-images.githubusercontent.com/3965182/197484991-70f87044-772f-4808-a412-d036490b1419.png)
![image](https://user-images.githubusercontent.com/3965182/197485029-540e79e7-52d0-4a4b-a753-183ce1f66f12.png)

**Comment by gangb-tech** [comment]
Fixed。
This error is caused by the test package。
