### ISSUE TITLE
[Bug] Table schema for segment_version may be wrong

### ISSUE THREAD

**Issue by hezean** [FeatureProbe/feature-probe-api#38]
In flyway `V38`, we defined
![Screenshot 2022-11-07 at 02 09 14](https://user-images.githubusercontent.com/49837965/200187603-fdc2512d-f966-4ff9-9e24-172bf7dbbb62.png)

but the JpaRepository defines the PK as Long
![Screenshot 2022-11-07 at 02 12 03](https://user-images.githubusercontent.com/49837965/200187738-a87f97bb-928c-4242-8ddb-15f943f31b4b.png)

which causes
<img width="1018" alt="Screenshot 2022-11-07 at 02 08 38" src="https://user-images.githubusercontent.com/49837965/200187541-eb66782b-e076-47b3-8a10-e36b4bb83d1a.png">

**Comment by HeZean** [comment]
BTW, there may need an integration test
